name: Build main

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main, gh-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the FPM Prod image
      run: docker build -t kimai/kimai2:fpm-master-prod --build-arg KIMAI=master --build-arg BASE=fpm --build-arg TZ=${TIMEZONE} --target=prod .
    - name: Test the image
      run: docker network create --driver bridge kimai-test
      run: docker run --rm --network kimai-test --name kimai-mysql-testing -e MYSQL_DATABASE=kimai -e MYSQL_USER=kimai -e MYSQL_PASSWORD=kimai -e MYSQL_ROOT_PASSWORD=kimai -p 3399:3306 -d mysql
      run: docker run --rm --network kimai-test --name kimai-test-fpm-master-prod -ti -e DATABASE_URL=mysql://kimai:kimai@kimai-mysql-testing:3306/kimai --entrypoint /self-test.sh kimai/kimai2:fpm-master-prod
